run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - gocritic
    - revive
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - bodyclose
    - noctx
    - nilerr

linters-settings:
  gocritic:
    disabled-checks:
      - ifElseChain
  revive:
    rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true
  goimports:
    local-prefixes: example.com/taskservice

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - unparam
        - errcheck
